define({
  root: ({
    widgetversion: 'eBookmark Widget Version Info',
    widgetverstr: 'Widget Version',
    wabversionmsg: 'Widget is designed to run in Web AppBuilder version',
    titlebookmarks: 'Bookmarks',
    placeholderBookmarkName: 'Bookmark Name',
    placeholderFolderName: 'Folder Name',
    errorNameExist: 'Name exists!',
    errorNameNull: "Invalid bookmark name!",
    labelDelete: "Delete",
    labelEdit: "Edit",
    labelBookmarkName: "Bookmark the current view",
    clearSelected: "Clear Selected",
    clearToolTip: "The selected node in the tree will determine where a new bookmark is added. To add a new bookmark in the root of the tree you need to clear the current selected node.",
    webmapfoldername: "Webmap Bookmarks",
    errorWebmapNode: "You can not add a boomark or folder to the webmap folder.",
    thumbPreview: "Preview the bookmark thumbnail image.",
    bookmarkPreview: "Bookmark Preview",
    bookmarkThumbnail: "Bookmark thumbnail",
    widgetactions: "Actions Menu",
    addBookmark: "Add Bookmark",
    addFolder: "Add Folder",
    saveBookmarks: "Save Bookmarks",
    expanded: "Folder expanded",
    cancel: "Cancel",
    add: "Add",
    ok: "Ok",
    loadBookmarks: "Load Bookmarks",
    exportBookmarkUri: "Export Bookmark Url"
  })
});
